config/routes.rb
VitalWatcher::Application.routes.draw do
  resources :event_types
  resources :activity_types

  resources :users
  resources :heart_rate_types

  resources :recover_passwords, :except => [:index, :show, :destroy] 
  
  resources :sessions, :only => [:new, :create, :destroy] do
    collection do
      post :authenticate
    end
  end

  resources :devices, :only => [:new, :create, :destroy] do
    member do
      get :show_user
    end
  end

  resources :heart_rate_summaries, :only => [:show] do
    member do
      get :show_user
    end
  end

  resources :activities, :only => [:show] do
    member do
      get :show_user
    end
  end  

  resources :events, :only => [:show] do
    member do
      get :show_user
    end
  end

  resources :marshalling, :only => [:index]

  match '/signup',                  :to => 'users#new'
  match '/signin',                  :to => 'sessions#new'
  match '/signout',                 :to => 'sessions#destroy'
  
  match '/configurations',          :to => 'pages#configurations'
  match '/about',                   :to => 'pages#about'
  match '/not_enough_privileges',   :to => 'pages#not_enough_privileges'

  root :to => 'pages#home'

end

app/controllers/heart_rate_types_controller.rb
class HeartRateTypesController < ApplicationController
  before_filter :authenticate
  before_filter :admin_user,  :except => :index

  # GET /heart_rate_types
  # GET /heart_rate_types.json
  def index
    @heart_rate_types = HeartRateType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @heart_rate_types }
    end
  end

  # GET /heart_rate_types/1
  # GET /heart_rate_types/1.json
  def show
    @heart_rate_type = HeartRateType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @heart_rate_type }
    end
  end

  # GET /heart_rate_types/new
  # GET /heart_rate_types/new.json
  def new
    @heart_rate_type = HeartRateType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @heart_rate_type }
    end
  end

  # GET /heart_rate_types/1/edit
  def edit
    @heart_rate_type = HeartRateType.find(params[:id])
  end

  # POST /heart_rate_types
  # POST /heart_rate_types.json
  def create
    @heart_rate_type = HeartRateType.new(params[:heart_rate_type])

    respond_to do |format|
      if @heart_rate_type.save
        format.html { redirect_to @heart_rate_type, notice: 'Heart rate type was successfully created.' }
        format.json { render json: @heart_rate_type, status: :created, location: @heart_rate_type }
      else
        format.html { render action: "new" }
        format.json { render json: @heart_rate_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /heart_rate_types/1
  # PUT /heart_rate_types/1.json
  def update
    @heart_rate_type = HeartRateType.find(params[:id])

    respond_to do |format|
      if @heart_rate_type.update_attributes(params[:heart_rate_type])
        format.html { redirect_to @heart_rate_type, notice: 'Heart rate type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @heart_rate_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heart_rate_types/1
  # DELETE /heart_rate_types/1.json
  def destroy
    @heart_rate_type = HeartRateType.find(params[:id])
    @heart_rate_type.destroy

    respond_to do |format|
      format.html { redirect_to heart_rate_types_url }
      format.json { head :ok }
    end
  end

  private
  
    
end

app/helpers/heart_rate_types_helper.rb
module HeartRateTypesHelper
end

app/views/heart_rate_types/_form.html.erb
<%= form_for(@heart_rate_type) do |f| %>
  <% if @heart_rate_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@heart_rate_type.errors.count, "error") %> prohibited this heart_rate_type from being saved:</h2>

      <ul>
      <% @heart_rate_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :min_value %><br />
    <%= f.number_field :min_value %>
  </div>
  <div class="field">
    <%= f.label :max_value %><br />
    <%= f.number_field :max_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/heart_rate_types/edit.html.erb
<h1>Editing heart_rate_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @heart_rate_type %> |
<%= link_to 'Back', heart_rate_types_path %>

app/views/heart_rate_types/index.html.erb
<h1>Heart Rate Groups</h1>

<table>
  <tr>
    <th>Between</th>
    <th>Min value</th>
    <th>Max value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @heart_rate_types.each do |heart_rate_type| %>
  <tr>
    <td><%= heart_rate_type.name %></td>
    <td><%= heart_rate_type.min_value %></td>
    <td><%= heart_rate_type.max_value %></td>

    <% if current_user.admin? %>
      <td><%= link_to 'Show', heart_rate_type %></td>
      <td><%= link_to 'Edit', edit_heart_rate_type_path(heart_rate_type) %></td>
      <td><%= link_to 'Destroy', heart_rate_type, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if current_user.admin? %>
  <%= link_to 'New Heart rate type', new_heart_rate_type_path %>
<% end %>

app/views/heart_rate_types/new.html.erb
<h1>New heart_rate_type</h1>

<%= render 'form' %>

<%= link_to 'Back', heart_rate_types_path %>

app/views/heart_rate_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @heart_rate_type.name %>
</p>

<p>
  <b>Min value:</b>
  <%= @heart_rate_type.min_value %>
</p>

<p>
  <b>Max value:</b>
  <%= @heart_rate_type.max_value %>
</p>


<%= link_to 'Edit', edit_heart_rate_type_path(@heart_rate_type) %> |
<%= link_to 'Back', heart_rate_types_path %>