config/routes.rb
VitalWatcher::Application.routes.draw do
  resources :event_types
  resources :activity_types

  resources :users
  resources :heart_rate_types

  resources :recover_passwords, :except => [:index, :show, :destroy] 
  
  resources :sessions, :only => [:new, :create, :destroy] do
    collection do
      post :authenticate
    end
  end

  resources :devices, :only => [:new, :create, :destroy] do
    member do
      get :show_user
    end
  end

  resources :heart_rate_summaries, :only => [:show] do
    member do
      get :show_user
    end
  end

  resources :activities, :only => [:show] do
    member do
      get :show_user
    end
  end  

  resources :events, :only => [:show] do
    member do
      get :show_user
    end
  end

  resources :marshalling, :only => [:index]

  match '/signup',                  :to => 'users#new'
  match '/signin',                  :to => 'sessions#new'
  match '/signout',                 :to => 'sessions#destroy'
  
  match '/configurations',          :to => 'pages#configurations'
  match '/about',                   :to => 'pages#about'
  match '/not_enough_privileges',   :to => 'pages#not_enough_privileges'

  root :to => 'pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>  from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.display_name %>
      </h1>
      <%= render 'shared/menu' %>
    </td>
    <td class="sidebar round">
      <%= render 'shared/sidebar' %>
    </td>
  </tr>
</table>

app/views/shared/_menu.html.erb
<nav class="round leftnav">
  <ul>
  	<li><%= link_to "Monitor", show_user_heart_rate_summary_path %></li>
  	<li><%= link_to "Activity", show_user_activity_path %></li>
  	<li><%= link_to "Events", show_user_event_path %></li>
  	<li><%= link_to "Devices", show_user_device_path(@user) %></li>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<strong>Name</strong> <%= @user.display_name %><br />
<strong>Login</strong> <%= @user.login %><br />
<strong>Email</strong> <%= @user.email %><br />
<strong>Status</strong>  <%= status_for @user %><br />
<strong>Heart Rate</strong> <%= @user.last_heart_rate %><br />





	

app/views/shared/_user_header.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= link_to @user.display_name, @user %>
      </h1>
      <%= render 'shared/menu' %>
    </td>
    <td class="sidebar round">
      <%= render 'shared/sidebar' %>
    </td>
  </tr>
</table>