config/routes.rb
VitalWatcher::Application.routes.draw do
  resources :event_types
  resources :activity_types

  resources :users
  resources :heart_rate_types

  resources :recover_passwords, :except => [:index, :show, :destroy] 
  
  resources :sessions, :only => [:new, :create, :destroy] do
    collection do
      post :authenticate
    end
  end

  resources :devices, :only => [:new, :create, :destroy] do
    member do
      get :show_user
    end
  end

  resources :heart_rate_summaries, :only => [:show] do
    member do
      get :show_user
    end
  end

  resources :activities, :only => [:show] do
    member do
      get :show_user
    end
  end  

  resources :events, :only => [:show] do
    member do
      get :show_user
    end
  end

  resources :marshalling, :only => [:index]

  match '/signup',                  :to => 'users#new'
  match '/signin',                  :to => 'sessions#new'
  match '/signout',                 :to => 'sessions#destroy'
  
  match '/configurations',          :to => 'pages#configurations'
  match '/about',                   :to => 'pages#about'
  match '/not_enough_privileges',   :to => 'pages#not_enough_privileges'

  root :to => 'pages#home'

end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  # GET /activity_types
  # GET /activity_types.json
  def index
    @activity_types = ActivityType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activity_types }
    end
  end

  # GET /activity_types/1
  # GET /activity_types/1.json
  def show
    @activity_type = ActivityType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity_type }
    end
  end

  # GET /activity_types/new
  # GET /activity_types/new.json
  def new
    @activity_type = ActivityType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity_type }
    end
  end

  # GET /activity_types/1/edit
  def edit
    @activity_type = ActivityType.find(params[:id])
  end

  # POST /activity_types
  # POST /activity_types.json
  def create
    @activity_type = ActivityType.new(params[:activity_type])

    respond_to do |format|
      if @activity_type.save
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully created.' }
        format.json { render json: @activity_type, status: :created, location: @activity_type }
      else
        format.html { render action: "new" }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activity_types/1
  # PUT /activity_types/1.json
  def update
    @activity_type = ActivityType.find(params[:id])

    respond_to do |format|
      if @activity_type.update_attributes(params[:activity_type])
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_types/1
  # DELETE /activity_types/1.json
  def destroy
    @activity_type = ActivityType.find(params[:id])
    @activity_type.destroy

    respond_to do |format|
      format.html { redirect_to activity_types_url }
      format.json { head :ok }
    end
  end
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
	def tag_for(value)
		"0x%02x" % value
	end
end

app/views/activity_types/_form.html.erb
<%= form_for(@activity_type) do |f| %>
  <% if @activity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_type.errors.count, "error") %> prohibited this activity_type from being saved:</h2>

      <ul>
      <% @activity_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_types/edit.html.erb
<h1>Editing activity_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity_type %> |
<%= link_to 'Back', activity_types_path %>

app/views/activity_types/index.html.erb
<h1>Activity Types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Tag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activity_types.each do |activity_type| %>
  <tr>
    <td><%= activity_type.name %></td>
    <td><%= tag_for activity_type.tag %></td>
    <td><%= link_to 'Show', activity_type %></td>
    <td><%= link_to 'Edit', edit_activity_type_path(activity_type) %></td>
    <td><%= link_to 'Destroy', activity_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity type', new_activity_type_path %>

app/views/activity_types/new.html.erb
<h1>New activity_type</h1>

<%= render 'form' %>

<%= link_to 'Back', activity_types_path %>

app/views/activity_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @activity_type.name %>
</p>

<p>
  <b>Tag:</b>
  <%= @activity_type.tag %>
</p>


<%= link_to 'Edit', edit_activity_type_path(@activity_type) %> |
<%= link_to 'Back', activity_types_path %>